#!/usr/bin/env bash
set -euo pipefail

mysql_root=(mysql --protocol=tcp --host=mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --default-character-set=utf8mb4)

"${mysql_root[@]}" --execute="
CREATE DATABASE IF NOT EXISTS \`${FLINK_LAB_MYSQL_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${FLINK_LAB_MYSQL_USER}'@'%' IDENTIFIED BY '${FLINK_LAB_MYSQL_PASSWORD}';
ALTER USER '${FLINK_LAB_MYSQL_USER}'@'%' IDENTIFIED BY '${FLINK_LAB_MYSQL_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX ON \`${FLINK_LAB_MYSQL_DATABASE}\`.* TO '${FLINK_LAB_MYSQL_USER}'@'%';
CREATE USER IF NOT EXISTS '${FLINK_LAB_MYSQL_CDC_USER}'@'%' IDENTIFIED BY '${FLINK_LAB_MYSQL_CDC_PASSWORD}';
ALTER USER '${FLINK_LAB_MYSQL_CDC_USER}'@'%' IDENTIFIED BY '${FLINK_LAB_MYSQL_CDC_PASSWORD}';
GRANT SELECT ON \`${FLINK_LAB_MYSQL_DATABASE}\`.* TO '${FLINK_LAB_MYSQL_CDC_USER}'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${FLINK_LAB_MYSQL_CDC_USER}'@'%';
FLUSH PRIVILEGES;"

"${mysql_root[@]}" "${FLINK_LAB_MYSQL_DATABASE}" < /opt/flink-food-lab/mysql/schema.sql
