import type { ReactNode } from "react"
import { AlertCircle, Inbox, Search } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { valueText } from "@/lib/format"

export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div> }
export function LoadingState({ label = "正在加载" }: { label?: string }) { return <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-muted-foreground"><Spinner />{label}</div> }
export function ErrorState({ error, retry }: { error: unknown; retry?: () => void }) { return <Alert variant="destructive"><AlertCircle data-icon="inline-start" /><AlertTitle>加载失败</AlertTitle><AlertDescription>{error instanceof Error ? error.message : "发生未知错误"}{retry && <Button className="ml-3" size="sm" variant="outline" onClick={retry}>重试</Button>}</AlertDescription></Alert> }
export function EmptyState({ title = "暂无数据", description = "调整筛选条件或创建第一条记录。", action }: { title?: string; description?: string; action?: ReactNode }) { return <Empty><EmptyHeader><EmptyMedia variant="icon"><Inbox /></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action && <EmptyContent>{action}</EmptyContent>}</Empty> }
export function SearchInput({ value, onChange, placeholder = "搜索…" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="relative w-full sm:w-72"><Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" data-icon="inline-start" /><Input className="pl-8" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} aria-label={placeholder} /></div> }
const statusLabels: Record<string, string> = { pending: "待处理", processing: "处理中", resolved: "已解决", ignored: "已忽略", timed_out: "已超时", partial_failed: "部分失败", sent: "已发送", failed: "发送失败", sending: "发送中", in_transit: "传输中", waiting: "等待处理", waiting_delivery: "等待投递", none: "未推送", uncertain: "结果待确认", aborted: "已中止", disabled: "未启用", skipped: "已跳过", online: "在线", offline: "离线", enabled: "已启用", synced: "已同步", sync_pending: "待同步", sync_error: "同步失败", low: "低", medium: "中", high: "高", critical: "严重" }
const statusLabel = (value?: string) => statusLabels[value ?? ""] ?? value ?? "未知"
export function StatusBadge({ value }: { value?: string }) { const variants: Record<string, string> = { resolved: "bg-success-subtle text-success", sent: "bg-success-subtle text-success", online: "bg-success-subtle text-success", enabled: "bg-success-subtle text-success", synced: "bg-success-subtle text-success", sync_pending: "bg-warning-subtle text-warning-foreground", sync_error: "bg-destructive text-destructive-foreground", pending: "bg-warning-subtle text-warning-foreground", processing: "bg-info-subtle text-info", sending: "bg-info-subtle text-info", in_transit: "bg-info-subtle text-info", waiting: "bg-warning-subtle text-warning-foreground", waiting_delivery: "bg-warning-subtle text-warning-foreground", timed_out: "bg-coral-subtle text-coral", partial_failed: "bg-coral-subtle text-coral", high: "bg-coral-subtle text-coral", critical: "bg-destructive text-destructive-foreground", failed: "bg-destructive text-destructive-foreground", medium: "bg-warning-subtle text-warning-foreground", low: "bg-info-subtle text-info", offline: "bg-muted text-muted-foreground", ignored: "bg-muted text-muted-foreground", disabled: "bg-muted text-muted-foreground", none: "bg-muted text-muted-foreground" }; return <Badge variant="secondary" className={variants[value ?? ""]}>{statusLabel(value)}</Badge> }
export function MetricCard({ title, value, description }: { title: string; value: ReactNode; description?: string }) { return <Card><CardHeader className="pb-2"><CardDescription>{title}</CardDescription><CardTitle className="metric-number">{value}</CardTitle></CardHeader>{description && <CardContent className="text-xs text-muted-foreground">{description}</CardContent>}</Card> }
export function StatisticCard({ title, value, description, accent = "primary" }: { title: string; value: ReactNode; description?: string; accent?: "primary" | "coral" | "success" | "warning" }) { const accentClass = { primary: "border-t-primary", coral: "border-t-coral", success: "border-t-success", warning: "border-t-warning" }[accent]; return <Card className={`border-t-2 ${accentClass}`}><CardHeader className="gap-1 p-4"><CardDescription className="text-xs font-semibold tracking-wide">{title}</CardDescription><CardTitle className="metric-number text-2xl">{value}</CardTitle>{description && <CardDescription>{description}</CardDescription>}</CardHeader></Card> }
export function DetailRow({ label, value }: { label: string; value: unknown }) { return <div className="grid gap-1 border-b py-3 text-sm sm:grid-cols-[10rem_minmax(0,1fr)] sm:gap-4"><dt className="font-medium text-muted-foreground">{label}</dt><dd className="min-w-0 break-words font-mono text-xs leading-5">{valueText(value)}</dd></div> }
export function DetailSection({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-lg border bg-card"><h2 className="border-b px-4 py-3 text-sm font-semibold">{title}</h2><dl className="px-4">{children}</dl></section> }
export function TablePagination({ page, pages, onPageChange }: { page: number; pages: number; onPageChange: (page: number) => void }) { if (pages <= 1) return null; return <Pagination className="justify-end"><PaginationContent><PaginationItem><PaginationPrevious href="#" onClick={(event) => { event.preventDefault(); if (page > 1) onPageChange(page - 1) }} aria-disabled={page <= 1} /></PaginationItem>{Array.from({ length: pages }, (_, index) => index + 1).slice(Math.max(0, page - 3), page + 2).map((item) => <PaginationItem key={item}><PaginationLink href="#" isActive={item === page} onClick={(event) => { event.preventDefault(); onPageChange(item) }}>{item}</PaginationLink></PaginationItem>)}<PaginationItem><PaginationNext href="#" onClick={(event) => { event.preventDefault(); if (page < pages) onPageChange(page + 1) }} aria-disabled={page >= pages} /></PaginationItem></PaginationContent></Pagination> }
export function IconTooltip({ label, children }: { label: string; children: ReactNode }) { return <Tooltip><TooltipTrigger asChild>{children}</TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip> }
