import { useEffect, useMemo, useRef, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Cable, Pencil, Plus, Trash2 } from "lucide-react"
import { toast } from "sonner"
import type { Datasource, DatasourceInput } from "@/api/types"
import { useApp } from "@/app/context"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { EmptyState, ErrorState, LoadingState, PageHeader, SearchInput, StatisticCard, StatusBadge } from "@/components/shared"
import { formatDateTime } from "@/lib/format"

const blank = (): DatasourceInput => ({ name: "", type: "mysql", host: "", port: 3306, database: "", username: "", password: "", ssl: false, description: "" })

export function DatasourcesPage() {
  const { resources } = useApp(); const client = useQueryClient(); const mounted = useRef(true); useEffect(() => () => { mounted.current = false }, [])
  const query = useQuery({ queryKey: ["datasources"], queryFn: ({ signal }) => resources.datasources.list(signal) })
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Datasource | "new" | null>(null); const [draft, setDraft] = useState<DatasourceInput>(blank); const [errors, setErrors] = useState<Record<string, string>>({})
  const filtered = useMemo(() => { const needle = search.trim().toLocaleLowerCase("zh-CN"); return (query.data ?? []).filter((item) => !needle || [item.name, item.host, item.database, item.username, item.description].some((value) => String(value ?? "").toLocaleLowerCase("zh-CN").includes(needle))) }, [query.data, search])
  const open = (value: Datasource | "new") => { setEditing(value); setDraft(value === "new" ? blank() : { name: value.name, type: value.type, host: value.host, port: value.port, database: value.database, username: value.username, password: "", ssl: value.ssl, description: value.description ?? "" }); setErrors({}) }
  const close = () => { if (!save.isPending && !configTest.isPending) setEditing(null) }
  const savedTest = useMutation({ mutationFn: (id: string) => resources.datasources.test(id), onSuccess: () => { client.invalidateQueries({ queryKey: ["datasources"] }); if (mounted.current) toast.success("连接测试成功") }, onError: (error) => { client.invalidateQueries({ queryKey: ["datasources"] }); if (mounted.current) toast.error(error.message) } })
  const configTest = useMutation({ mutationFn: () => resources.datasources.testConfig({ ...draft, id: editing === "new" ? undefined : editing?.id }), onSuccess: () => { if (mounted.current && editing) toast.success("配置连接成功") }, onError: (error) => { if (mounted.current && editing) toast.error(error.message) } })
  const save = useMutation({ mutationFn: () => editing === "new" ? resources.datasources.create(draft) : resources.datasources.update((editing as Datasource).id, draft), onSuccess: () => { client.invalidateQueries({ queryKey: ["datasources"] }); if (mounted.current && editing) { toast.success(editing === "new" ? "数据源已创建" : "数据源已更新"); setEditing(null) } }, onError: (error) => { if (mounted.current && editing) toast.error(error.message) } })
  const remove = useMutation({ mutationFn: (id: string) => resources.datasources.remove(id), onSuccess: () => { client.invalidateQueries({ queryKey: ["datasources"] }); if (mounted.current) toast.success("数据源已删除") }, onError: (error) => { if (mounted.current) toast.error(`删除失败：${error.message}`) } })
  const submit = () => { if (save.isPending) return; const next: Record<string, string> = {}; for (const key of ["name", "host", "database", "username"] as const) if (!String(draft[key]).trim()) next[key] = "此项必填"; if (!Number.isFinite(Number(draft.port)) || Number(draft.port) <= 0) next.port = "请输入有效端口"; setErrors(next); if (!Object.keys(next).length) save.mutate() }
  const all = query.data ?? []; const online = all.filter((item) => item.status === "online").length; const failing = all.filter((item) => item.status === "error" || item.status === "offline").length; const savedTestId = savedTest.isPending ? savedTest.variables : undefined; const removeId = remove.isPending ? remove.variables : undefined
  return <div className="page-grid"><PageHeader title="数据源" description="管理数据库连接；编辑时留空密码会保留当前凭据" actions={<Button onClick={() => open("new")}><Plus data-icon="inline-start" />新建数据源</Button>} />
    <div className="grid gap-3 sm:grid-cols-3"><StatisticCard title="数据源总数" value={all.length} description="已配置连接" /><StatisticCard title="在线" value={online} description="最近测试成功" accent="success" /><StatisticCard title="需检查" value={failing} description="离线或连接失败" accent="coral" /></div>
    <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><SearchInput value={search} onChange={setSearch} placeholder="搜索数据源" /><span className="text-xs text-muted-foreground">共 {filtered.length} 个数据源</span></div>
    {query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()} /> : !filtered.length ? <EmptyState title={search ? "没有匹配的数据源" : "还没有数据源"} description={search ? "尝试调整搜索条件。" : "创建第一个数据库连接。"} /> : <Card className="overflow-x-auto"><Table className="dense-table"><TableHeader><TableRow><TableHead>名称</TableHead><TableHead>类型</TableHead><TableHead>地址</TableHead><TableHead>数据库</TableHead><TableHead>状态</TableHead><TableHead>最近检查</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((item) => <TableRow key={item.id}><TableCell><div className="font-medium">{item.name}</div><div className="max-w-64 truncate text-xs text-muted-foreground">{item.description || item.username}</div></TableCell><TableCell className="uppercase">{item.type}</TableCell><TableCell className="font-mono text-xs">{item.host}:{item.port}</TableCell><TableCell>{item.database}</TableCell><TableCell><div className="space-y-1"><StatusBadge value={item.status} />{(item.error_message || item.error_msg) && <div className="max-w-56 break-words text-xs text-destructive">{item.error_message || item.error_msg}</div>}</div></TableCell><TableCell>{formatDateTime(item.last_checked)}</TableCell><TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon-sm" aria-label={`测试 ${item.name}`} disabled={savedTestId === item.id} onClick={() => { if (!savedTest.isPending) savedTest.mutate(item.id) }}><Cable /></Button><Button variant="ghost" size="icon-sm" aria-label={`编辑 ${item.name}`} onClick={() => open(item)}><Pencil /></Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`删除 ${item.name}`} disabled={removeId === item.id}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除数据源？</AlertDialogTitle><AlertDialogDescription>后端会阻止删除仍被数据集、SQL 校验或未完成异常引用的数据源。确认继续？</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={remove.isPending} onClick={() => { if (!remove.isPending) remove.mutate(item.id) }}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableCell></TableRow>)}</TableBody></Table></Card>}
    <Dialog open={Boolean(editing)} onOpenChange={(value) => { if (!value) close() }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing === "new" ? "新建数据源" : "编辑数据源"}</DialogTitle><DialogDescription>{editing === "new" ? "填写数据库连接与认证凭据。" : "数据库类型不可修改；密码留空会继续使用已保存凭据。"}</DialogDescription></DialogHeader><FieldGroup>{(["name", "host", "database", "username"] as const).map((key) => <Field key={key} data-invalid={Boolean(errors[key])}><FieldLabel htmlFor={`source-${key}`}>{({ name: "名称", host: "主机", database: "数据库", username: "用户名" })[key]}</FieldLabel><Input id={`source-${key}`} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} aria-invalid={Boolean(errors[key])} /><FieldError>{errors[key]}</FieldError></Field>)}<div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field><FieldLabel>类型</FieldLabel><Select disabled={editing !== "new"} value={draft.type} onValueChange={(type) => setDraft({ ...draft, type, port: type === "starrocks" ? 9030 : 3306 })}><SelectTrigger aria-label="数据库类型"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mysql">MySQL</SelectItem><SelectItem value="starrocks">StarRocks</SelectItem><SelectItem value="postgresql">PostgreSQL</SelectItem><SelectItem value="clickhouse">ClickHouse</SelectItem></SelectContent></Select><FieldDescription>{editing !== "new" && "保存后类型不可变"}</FieldDescription></Field><Field data-invalid={Boolean(errors.port)}><FieldLabel htmlFor="source-port">端口</FieldLabel><Input id="source-port" type="number" value={draft.port} onChange={(event) => setDraft({ ...draft, port: event.target.value })} aria-invalid={Boolean(errors.port)} /><FieldError>{errors.port}</FieldError></Field></div><Field><FieldLabel htmlFor="source-password">密码</FieldLabel><Input id="source-password" type="password" autoComplete="new-password" value={draft.password} onChange={(event) => setDraft({ ...draft, password: event.target.value })} /><FieldDescription>{editing !== "new" ? "留空将保留当前密码；测试也会使用已保存凭据。" : "凭据仅发送给当前后端。"}</FieldDescription></Field><Field><FieldLabel htmlFor="source-description">描述</FieldLabel><Input id="source-description" value={draft.description ?? ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Field><Field orientation="horizontal"><FieldLabel htmlFor="source-ssl">SSL 加密</FieldLabel><Switch id="source-ssl" checked={Boolean(draft.ssl)} onCheckedChange={(ssl) => setDraft({ ...draft, ssl })} /></Field></FieldGroup><DialogFooter><Button variant="outline" disabled={configTest.isPending || save.isPending} onClick={() => { if (!configTest.isPending) configTest.mutate() }}>{configTest.isPending ? "测试中…" : "测试配置"}</Button><Button disabled={save.isPending || configTest.isPending} onClick={submit}>{save.isPending ? "保存中…" : "保存"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
