import { useEffect, useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { ExternalLink } from "lucide-react"
import { useApp } from "@/app/context"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DetailRow, DetailSection, EmptyState, ErrorState, LoadingState, PageHeader, SearchInput, StatusBadge, TablePagination } from "@/components/shared"
import { formatDateTime, valueText } from "@/lib/format"
import type { AnomalyGroup } from "@/api/types"

function Summary({ group }: { group: AnomalyGroup }) { return <div className="grid gap-1"><span className="font-mono">{group.scanned_rows ?? 0} / {group.matched_rows ?? 0} / {group.new_anomalies ?? 0}</span><span className="text-xs text-muted-foreground">待 {group.pending_count ?? 0} · 中 {group.processing_count ?? 0} · 解 {group.resolved_count ?? 0} · 超 {group.timed_out_count ?? 0}</span></div> }

export function GroupsPage({ detailId, navigate }: { detailId?: string; navigate: (hash: string) => void }) {
  const { resources } = useApp(); const [page, setPage] = useState(1); const [input, setInput] = useState(""); const [search, setSearch] = useState(""); const [memberPaging, setMemberPaging] = useState({ id: detailId, page: 1 }); const membersPage = memberPaging.id === detailId ? memberPaging.page : 1
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(input); setPage(1) }, 250); return () => window.clearTimeout(timer) }, [input])
  const query = useQuery({ queryKey: ["groups", { page, search }], queryFn: ({ signal }) => resources.groups.list({ page, pageSize: 20, search }, signal), placeholderData: (previous) => previous })
  const detail = useQuery({ queryKey: ["group", detailId, membersPage], queryFn: ({ signal }) => resources.groups.detail(detailId!, { page: membersPage, pageSize: 20 }, signal), enabled: Boolean(detailId) })
  const items = query.data?.items ?? []; const pages = query.data?.pages ?? Math.max(1, Math.ceil((query.data?.total ?? 0) / 20)); const memberPages = detail.data ? Math.max(1, Math.ceil((detail.data.total ?? detail.data.records.length) / (detail.data.page_size ?? 20))) : 1
  const open = (id: string) => navigate(`#anomaly-groups/${encodeURIComponent(id)}`); const rowKeys = (event: React.KeyboardEvent, id: string) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open(id) } }
  return <div className="page-grid"><PageHeader title="异常记录组" description="按规则和检测批次聚合异常及播报情况" /><Card><CardContent className="pt-4"><SearchInput value={input} onChange={setInput} placeholder="搜索规则名称…" /></CardContent></Card>{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()} /> : !items.length ? <EmptyState title="暂无异常记录组" description="当前筛选条件下没有检测批次。" /> : <><Card className="hidden overflow-x-auto md:block"><Table className="dense-table"><TableHeader><TableRow><TableHead>规则</TableHead><TableHead>检测时间</TableHead><TableHead>扫描 / 命中 / 新增</TableHead><TableHead>处理状态</TableHead><TableHead>异常情况播报</TableHead><TableHead>超时播报</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id} tabIndex={0} role="button" aria-label={`查看 ${item.rule_name || item.id} 记录组`} className="cursor-pointer" onClick={() => open(item.id)} onKeyDown={(event) => rowKeys(event, item.id)}><TableCell className="font-medium">{item.rule_name || "未关联规则"}</TableCell><TableCell>{formatDateTime(item.last_detected_at || item.first_detected_at)}</TableCell><TableCell><Summary group={item} /></TableCell><TableCell><div className="flex flex-wrap gap-1 text-xs"><span>待 {item.pending_count ?? 0}</span><span>· 中 {item.processing_count ?? 0}</span><span>· 解 {item.resolved_count ?? 0}</span><span>· 超 {item.timed_out_count ?? 0}</span></div></TableCell><TableCell><StatusBadge value={item.situation_broadcast_status} /></TableCell><TableCell><StatusBadge value={item.timeout_broadcast_status} /></TableCell></TableRow>)}</TableBody></Table></Card><div className="grid gap-3 md:hidden">{items.map((item) => <Card key={item.id} tabIndex={0} role="button" aria-label={`查看 ${item.rule_name || item.id} 记录组`} onClick={() => open(item.id)} onKeyDown={(event) => rowKeys(event, item.id)}><CardContent className="space-y-2 pt-4"><p className="font-medium">{item.rule_name || "未关联规则"}</p><p className="text-xs text-muted-foreground">{formatDateTime(item.last_detected_at || item.first_detected_at)}</p><Summary group={item} /><div className="flex gap-2"><StatusBadge value={item.situation_broadcast_status} /><StatusBadge value={item.timeout_broadcast_status} /></div></CardContent></Card>)}</div><div className="flex justify-between text-sm"><span>共 {query.data?.total ?? 0} 组</span><TablePagination page={page} pages={pages} onPageChange={setPage} /></div></>}
    <Sheet open={Boolean(detailId)} onOpenChange={(visible) => { if (!visible) navigate("#anomaly-groups") }}><SheetContent className="w-full overflow-y-auto sm:max-w-3xl"><SheetHeader><SheetTitle>异常记录组详情</SheetTitle><SheetDescription>{detail.data?.rule_name || detailId}</SheetDescription></SheetHeader><div className="space-y-4 px-4 pb-6">{detail.isLoading ? <LoadingState /> : detail.error ? <ErrorState error={detail.error} /> : detail.data && <><DetailSection title="概览"><DetailRow label="检测时间" value={formatDateTime(detail.data.last_detected_at || detail.data.first_detected_at)} /><DetailRow label="扫描 / 命中 / 新增" value={`${detail.data.scanned_rows ?? 0} / ${detail.data.matched_rows ?? 0} / ${detail.data.new_anomalies ?? 0}`} /><DetailRow label="处理状态" value={`待处理 ${detail.data.pending_count ?? 0} · 处理中 ${detail.data.processing_count ?? 0} · 已解决 ${detail.data.resolved_count ?? 0} · 已超时 ${detail.data.timed_out_count ?? 0}`} /></DetailSection><DetailSection title="投递诊断">{detail.data.deliveries.length ? detail.data.deliveries.map((item, index) => <DetailRow key={item.id || index} label={`${item.kind} · ${item.status}`} value={{ attempts: item.attempts, error: item.error, sent_at: item.sent_at }} />) : <DetailRow label="播报" value="暂无播报诊断" />}</DetailSection><section className="rounded-lg border bg-card"><h2 className="border-b px-4 py-3 text-sm font-semibold">组内异常记录</h2>{detail.data.records.length ? <><div className="overflow-x-auto"><Table className="dense-table"><TableHeader><TableRow><TableHead>业务主键</TableHead><TableHead>状态</TableHead><TableHead>严重程度</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{detail.data.records.map((record) => <TableRow key={record.id}><TableCell className="max-w-64 truncate" title={valueText(record.business_key)}>{record.business_key_summary || record.anomaly_key || record.id}</TableCell><TableCell><StatusBadge value={record.status} /></TableCell><TableCell><StatusBadge value={record.severity} /></TableCell><TableCell><Button size="sm" variant="ghost" onClick={() => navigate(`#records/${encodeURIComponent(record.id)}`)}>查看明细 <ExternalLink data-icon="inline-end" /></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="p-3"><TablePagination page={membersPage} pages={memberPages} onPageChange={(next) => setMemberPaging({ id: detailId, page: next })} /></div></> : <div className="p-4 text-sm text-muted-foreground">本次未检测到异常记录</div>}</section></>}</div></SheetContent></Sheet></div>
}
