import { useMemo, useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { Activity, Database, RefreshCw, ShieldAlert, Zap } from "lucide-react"
import { useApp } from "@/app/context"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { EmptyState, ErrorState, LoadingState, PageHeader, StatisticCard, StatusBadge } from "@/components/shared"
import { formatDateTime } from "@/lib/format"

const severityLabels: Record<string, string> = { critical: "严重", high: "高", medium: "中", low: "低" }
const severityColors: Record<string, string> = { critical: "bg-destructive", high: "bg-coral", medium: "bg-warning", low: "bg-info" }

export function OverviewPage() {
  const { resources } = useApp(); const [days, setDays] = useState(30); const requestedDays = days === 7 ? 14 : days
  const query = useQuery({ queryKey: ["overview", days], queryFn: ({ signal }) => resources.overview(requestedDays, signal) })
  const data = query.data; const stats = data?.stats ?? {}; const rawTrend = data?.trend ?? []; const trend = days === 7 ? rawTrend.slice(-7) : rawTrend; const maximum = Math.max(1, ...trend.map((item) => Number(item.count) || 0))
  const severity = useMemo(() => (data?.severity_distribution ?? []).map((item) => ({ severity: String(item.severity ?? ""), count: Number(item.count ?? 0) })), [data?.severity_distribution]); const severityTotal = severity.reduce((sum, item) => sum + item.count, 0)
  if (query.isLoading && !data) return <LoadingState label="正在汇总监控数据" />
  if (query.error && !data) return <ErrorState error={query.error} retry={() => query.refetch()} />
  return <div className="page-grid"><PageHeader title="总览" description={`近 ${days} 天异常态势 · 北京时间（UTC+8）`} actions={<Button variant="outline" disabled={query.isFetching} onClick={() => query.refetch()}><RefreshCw data-icon="inline-start" className={query.isFetching ? "animate-spin" : ""} />{query.isFetching ? "刷新中…" : "刷新"}</Button>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatisticCard title="活跃规则" value={<>{stats.active_rules ?? 0}<span className="ml-1 text-sm font-normal text-muted-foreground">/ {stats.total_rules ?? 0}</span></>} description="启用 / 总数" /><StatisticCard title="待处理异常" value={(stats.pending_records ?? 0) + (stats.processing_records ?? 0) + (stats.timed_out_records ?? 0)} description={`${stats.pending_records ?? 0} 未处理 · ${stats.processing_records ?? 0} 处理中 · ${stats.timed_out_records ?? 0} 超时`} accent="coral" /><StatisticCard title="数据源在线" value={<>{stats.online_datasources ?? 0}<span className="ml-1 text-sm font-normal text-muted-foreground">/ {stats.total_datasources ?? 0}</span></>} description="在线 / 总数" accent="success" /><StatisticCard title="已解决异常" value={stats.resolved_records ?? 0} description="累计闭环" /></div>
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><Card className="min-w-0"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="flex items-center gap-2"><Activity />异常趋势 · 近 {days} 天</CardTitle><CardDescription>每日首次检出异常数量 · 北京时间（UTC+8）</CardDescription></div><div className="flex rounded-lg border bg-muted/40 p-1" aria-label="趋势时间范围">{[7, 30, 90].map((range) => <Button key={range} size="sm" variant={days === range ? "default" : "ghost"} disabled={query.isFetching} onClick={() => setDays(range)}>{range} 天</Button>)}</div></div></CardHeader><CardContent><div className="overflow-x-auto pb-2" tabIndex={0} aria-label="每日异常趋势，可横向滚动查看全部日期"><div className="flex h-56 items-end gap-1" style={{ minWidth: `${Math.max(trend.length * 18, 320)}px` }}>{trend.map((point, index) => { const count = Number(point.count) || 0; const height = count === 0 ? 0 : Math.max(8, Math.round((count / maximum) * 150)); return <div className="flex min-w-0 flex-1 flex-col items-center gap-1" key={point.date}><span className="font-mono text-[10px] text-muted-foreground">{count}</span><div data-trend-date={point.date} data-count={count} className={`w-full rounded-t ${index === trend.length - 1 ? "bg-coral" : "bg-primary/70"}`} style={{ height: `${height}px` }} title={`${point.date} · ${count} 次（北京时间）`} /><span className="h-4 whitespace-nowrap text-[10px] text-muted-foreground">{trend.length <= 14 || index % 7 === 0 || index === trend.length - 1 ? point.date.slice(5) : ""}</span></div> })}</div></div>{!trend.length && <EmptyState title="暂无趋势数据" description="当前时间范围内没有服务端趋势数据。" />}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert />严重级别分布</CardTitle><CardDescription>仅展示服务端返回的分布</CardDescription></CardHeader><CardContent>{!severity.length ? <EmptyState title="暂无严重级别分布数据" description="后端尚未提供该指标。" /> : <div className="space-y-4">{severity.map((item) => { const ratio = severityTotal > 0 ? item.count / severityTotal : 0; return <div className="space-y-1.5" key={item.severity}><div className="flex items-center justify-between text-sm"><span>{severityLabels[item.severity] ?? item.severity}</span><span className="font-mono">{item.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full ${severityColors[item.severity] ?? "bg-primary"}`} style={{ width: `${Math.max(0, Math.min(100, ratio * 100))}%` }} /></div></div> })}</div>}</CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Database />最近异常</CardTitle></CardHeader><CardContent className="p-0">{!data?.recent_anomalies?.length ? <EmptyState title="近期无异常" description="服务端没有返回最近异常。" /> : <div className="divide-y">{data.recent_anomalies.map((item) => <a href={`#records/${encodeURIComponent(item.id)}`} className="flex items-center gap-3 px-4 py-3 hover:bg-muted/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" key={item.id}><div className="min-w-0 flex-1"><div className="truncate font-medium">{item.rule_name || item.title || item.id}</div><div className="truncate text-xs text-muted-foreground">{formatDateTime(item.detected_at)} · {item.dataset_name || "未标注数据集"}</div></div><StatusBadge value={item.severity} /><StatusBadge value={item.status} /></a>)}</div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Zap />触发最多的规则</CardTitle></CardHeader><CardContent className="p-0">{!data?.top_rules?.length ? <EmptyState title="暂无规则排行" description="服务端没有返回规则统计。" /> : <div className="divide-y">{data.top_rules.map((item) => <a href={`#rules/${encodeURIComponent(String(item.id ?? ""))}/edit`} className="flex items-center gap-3 px-4 py-3 hover:bg-muted/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" key={String(item.id)}><div className="min-w-0 flex-1"><div className="truncate font-medium">{String(item.name ?? "未命名规则")}</div><div className="truncate text-xs text-muted-foreground">{String(item.dataset_name ?? "未标注数据集")}</div></div><div className="text-right"><div className="font-mono font-semibold">{Number(item.anomaly_count ?? 0)}</div><div className="text-xs text-muted-foreground">次</div></div></a>)}</div>}</CardContent></Card></div>
  </div>
}
