import { useEffect, useMemo, useRef, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { KeyRound, Pencil, Plus, RotateCcw, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { ApiError } from "@/api/client"
import type { User } from "@/api/types"
import { useApp } from "@/app/context"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { EmptyState, ErrorState, LoadingState, PageHeader, SearchInput, StatusBadge } from "@/components/shared"

function useMounted() { const mounted = useRef(false); useEffect(() => { mounted.current = true; return () => { mounted.current = false } }, []); return mounted }
function text(value: unknown) { return typeof value === "string" || typeof value === "number" ? String(value) : "0" }
function record(value: unknown): Record<string, unknown> | null { return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null }

type PushKind = "recover" | "clear" | "abort"
const pushMeta: Record<PushKind, { button: string; confirm: string; title: string; description: string; variant?: "destructive" }> = {
  recover: { button: "恢复待推送", confirm: "确认恢复", title: "恢复失败推送？", description: "只恢复后端判定为可安全重试的失败任务，不会重复发送已完成任务。" },
  clear: { button: "清理传输中", confirm: "确认清理", title: "清理所有在途推送？", description: "将处理所有筛选与分页之外的在途异常、群聊播报和关联任务。" },
  abort: { button: "中止全部推送", confirm: "确认中止", title: "中止推送积压？", description: "将停止尚未完成的推送任务；已经发送的消息无法撤回。", variant: "destructive" },
}

function pushSummary(kind: PushKind, result: Record<string, unknown>) {
  const summary = kind === "recover" ? `已重新入队 ${text(result.requeued_jobs)} 个任务，跳过 ${text(result.skipped_jobs)} 个任务。` : kind === "clear" ? `已解决 ${text(result.resolved_records)} 条在途异常，取消 ${text(result.cancelled_jobs)} 个任务。` : `已中止 ${text(result.aborted_jobs)} 个任务，停止 ${text(result.stopped_ds_instances)} 个调度实例。`
  const errors = Array.isArray(result.errors) ? result.errors.map(record).filter((item): item is Record<string, unknown> => Boolean(item)).map((item) => `${text(item.stage)}：${text(item.message)}`).join("；") : ""
  return errors ? `${summary} ${errors}` : summary
}

export function TestsPage() {
  const { resources, user } = useApp(); const mounted = useMounted(); const [receiveType, setReceiveType] = useState("open_id"); const [receiveId, setReceiveId] = useState(""); const [feishuResult, setFeishuResult] = useState<Record<string, unknown> | null>(null); const [pushResult, setPushResult] = useState<{ kind: PushKind; result: Record<string, unknown> } | null>(null)
  const send = useMutation({ mutationFn: () => resources.tests.feishu(receiveType, receiveId.trim()), onSuccess: (result) => { if (mounted.current) { setFeishuResult(result); toast.success("飞书测试消息已发送") } }, onError: (error) => { if (mounted.current) toast.error(error.message) } })
  const push = useMutation({ mutationFn: (kind: PushKind) => kind === "abort" ? resources.pushes.abort() : kind === "clear" ? resources.pushes.clear() : resources.pushes.recover(), onSuccess: (result, kind) => { if (mounted.current) { setPushResult({ kind, result }); toast.success("推送队列操作完成") } }, onError: (error, kind) => { if (!mounted.current) return; const details = error instanceof ApiError && error.status === 502 ? record(error.details) : null; if (details) setPushResult({ kind, result: details }); toast.error(error.message) } })
  if (!user.is_superuser) return <ErrorState error={new Error("需要超级管理员权限")} />
  return <div className="page-grid"><PageHeader title="系统测试" description="验证飞书目标与管理员推送队列处置能力" /><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>飞书测试消息</CardTitle><CardDescription>与异常通知共用真实发送链路，不会执行规则或生成异常。</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel>标识类型</FieldLabel><Select value={receiveType} onValueChange={(value) => { setReceiveType(value); setFeishuResult(null) }}><SelectTrigger aria-label="飞书标识类型"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open_id">open_id · 应用内用户</SelectItem><SelectItem value="union_id">union_id · 开发商内用户</SelectItem><SelectItem value="user_id">user_id · 租户内用户</SelectItem><SelectItem value="email">email · 用户邮箱</SelectItem><SelectItem value="chat_id">chat_id · 群聊</SelectItem></SelectContent></Select></Field><Field><FieldLabel htmlFor="receive-id">接收者标识</FieldLabel><Input id="receive-id" value={receiveId} onChange={(event) => setReceiveId(event.target.value)} maxLength={255} autoComplete="off" placeholder="填写与标识类型匹配的真实 ID" /></Field><Button disabled={!receiveId.trim() || send.isPending} onClick={() => { if (!send.isPending) send.mutate() }}>{send.isPending ? "发送中…" : "发送测试消息"}</Button>{feishuResult && <Alert><AlertTitle>消息发送成功</AlertTitle><AlertDescription className="font-mono text-xs">message_id: {String(feishuResult.message_id ?? "未返回")}</AlertDescription></Alert>}</FieldGroup></CardContent></Card><Card><CardHeader><CardTitle>推送队列处置</CardTitle><CardDescription>每项操作都会影响全局队列，需二次确认。</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{(Object.keys(pushMeta) as PushKind[]).map((kind) => { const meta = pushMeta[kind]; return <AlertDialog key={kind}><AlertDialogTrigger asChild><Button variant={meta.variant ?? "outline"} disabled={push.isPending}>{meta.button}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{meta.title}</AlertDialogTitle><AlertDialogDescription>{meta.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction variant={meta.variant} disabled={push.isPending} onClick={() => { if (!push.isPending) push.mutate(kind) }}>{meta.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> })}</div>{pushResult && <Alert><AlertTitle>{pushResult.result.status === "partial_failed" ? `${pushResult.kind === "recover" ? "失败推送" : pushResult.kind === "clear" ? "在途推送" : "推送积压"}部分失败` : pushResult.kind === "recover" ? "失败推送已恢复" : pushResult.kind === "clear" ? "在途推送已清理" : "推送积压已中止"}</AlertTitle><AlertDescription>{pushSummary(pushResult.kind, pushResult.result)}</AlertDescription></Alert>}</CardContent></Card></div></div>
}

export function AccountPage() {
  const { resources, user, setUser } = useApp(); const mounted = useMounted(); const [profile, setProfile] = useState({ display_name: user.display_name, job_title: user.job_title ?? "" }); const [credentials, setCredentials] = useState({ login_name: user.login_name, password: "" }); const [errors, setErrors] = useState<Record<string, string>>({})
  const profileMutation = useMutation({ mutationFn: () => resources.account.profile({ display_name: profile.display_name.trim(), job_title: profile.job_title.trim() }), onSuccess: (next) => { if (mounted.current) { setUser(next); toast.success("个人资料已保存") } }, onError: (error) => { if (mounted.current) toast.error(error.message) } })
  const credentialMutation = useMutation({ mutationFn: () => resources.account.credentials({ login_name: credentials.login_name.trim(), ...(credentials.password ? { password: credentials.password } : {}) }), onSuccess: (next) => { if (mounted.current) { setUser(next); setCredentials({ login_name: next.login_name, password: "" }); toast.success("登录设置已保存") } }, onError: (error) => { if (mounted.current) toast.error(error.message) } })
  const saveProfile = () => { if (profileMutation.isPending) return; if (!profile.display_name.trim()) { setErrors({ profile: "请输入显示名称" }); return } setErrors({}); profileMutation.mutate() }
  const saveCredentials = () => { if (credentialMutation.isPending) return; if (!credentials.login_name.trim()) { setErrors({ credentials: "请输入登录名" }); return } setErrors({}); credentialMutation.mutate() }
  return <div className="page-grid"><PageHeader title="个人账号" description="维护显示信息和登录凭据" /><Card><CardContent className="flex flex-col gap-4 pt-2 sm:flex-row sm:items-center"><div className="grid size-14 place-items-center rounded-xl bg-primary text-lg font-semibold text-primary-foreground">{user.display_name.slice(0, 2)}</div><div><div className="text-lg font-semibold">{user.display_name}</div><div className="text-sm text-muted-foreground">@{user.login_name} · {user.is_superuser ? "超级管理员" : user.job_title || "普通账号"}</div></div><StatusBadge value={user.is_active === false ? "disabled" : "enabled"} /></CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>个人资料</CardTitle><CardDescription>这些信息会显示在侧栏和账号列表中。</CardDescription></CardHeader><CardContent><FieldGroup><Field data-invalid={Boolean(errors.profile)}><FieldLabel htmlFor="display-name">显示名称</FieldLabel><Input id="display-name" autoComplete="name" value={profile.display_name} onChange={(event) => setProfile({ ...profile, display_name: event.target.value })} aria-invalid={Boolean(errors.profile)} /><FieldError>{errors.profile}</FieldError></Field><Field><FieldLabel htmlFor="job-title">职位</FieldLabel><Input id="job-title" value={profile.job_title} onChange={(event) => setProfile({ ...profile, job_title: event.target.value })} /></Field><Button disabled={profileMutation.isPending} onClick={saveProfile}>{profileMutation.isPending ? "保存中…" : "保存资料"}</Button></FieldGroup></CardContent></Card><Card><CardHeader><CardTitle>登录与安全</CardTitle><CardDescription>修改登录设置后，其他设备上的会话会失效。</CardDescription></CardHeader><CardContent><FieldGroup><Field data-invalid={Boolean(errors.credentials)}><FieldLabel htmlFor="account-login-name">登录名</FieldLabel><Input id="account-login-name" autoComplete="username" value={credentials.login_name} onChange={(event) => setCredentials({ ...credentials, login_name: event.target.value })} aria-invalid={Boolean(errors.credentials)} /><FieldError>{errors.credentials}</FieldError></Field><Field><FieldLabel htmlFor="new-password">新密码</FieldLabel><Input id="new-password" type="password" autoComplete="new-password" value={credentials.password} onChange={(event) => setCredentials({ ...credentials, password: event.target.value })} /><FieldDescription>留空表示不修改密码。</FieldDescription></Field><Button disabled={credentialMutation.isPending} onClick={saveCredentials}>{credentialMutation.isPending ? "更新中…" : "更新凭据"}</Button></FieldGroup></CardContent></Card></div></div>
}

type AccountDraft = { display_name: string; job_title: string; login_name: string; password: string; is_superuser: boolean; is_active: boolean }
const emptyAccount = (): AccountDraft => ({ display_name: "", job_title: "", login_name: "", password: "", is_superuser: false, is_active: true })

export function AccountsPage() {
  const { resources, user, setUser } = useApp(); const client = useQueryClient(); const mounted = useMounted(); const [search, setSearch] = useState(""); const [editor, setEditor] = useState<User | "new" | null>(null); const [draft, setDraft] = useState<AccountDraft>(emptyAccount); const [resetting, setResetting] = useState<User | null>(null); const [password, setPassword] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({})
  const query = useQuery({ queryKey: ["accounts"], queryFn: ({ signal }) => resources.accounts.list(signal), enabled: user.is_superuser })
  const filtered = useMemo(() => { const needle = search.trim().toLocaleLowerCase("zh-CN"); return (query.data ?? []).filter((item) => !needle || [item.display_name, item.login_name, item.job_title].some((value) => String(value ?? "").toLocaleLowerCase("zh-CN").includes(needle))) }, [query.data, search])
  const openEditor = (account: User | "new") => { setEditor(account); setErrors({}); setDraft(account === "new" ? emptyAccount() : { display_name: account.display_name, job_title: account.job_title ?? "", login_name: account.login_name, password: "", is_superuser: account.is_superuser, is_active: account.is_active !== false }) }
  const save = useMutation({ mutationFn: () => { const payload = { display_name: draft.display_name.trim(), job_title: draft.job_title.trim(), login_name: draft.login_name.trim(), is_superuser: draft.is_superuser, ...(editor === "new" ? { password: draft.password } : { is_active: draft.is_active }) }; return editor === "new" ? resources.accounts.create(payload) : resources.accounts.update((editor as User).id, payload) }, onSuccess: (next) => { client.invalidateQueries({ queryKey: ["accounts"] }); if (mounted.current && editor) { if (editor !== "new" && editor.id === user.id) setUser(next); toast.success(editor === "new" ? "账号已创建" : "账号已更新"); setEditor(null) } }, onError: (error) => { if (mounted.current && editor) toast.error(error.message) } })
  const reset = useMutation({ mutationFn: () => resources.accounts.password(resetting!.id, password), onSuccess: () => { if (mounted.current && resetting) { toast.success("密码已重置"); setResetting(null); setPassword("") } }, onError: (error) => { if (mounted.current && resetting) toast.error(error.message) } })
  const remove = useMutation({ mutationFn: (id: string) => resources.accounts.remove(id), onSuccess: () => { client.invalidateQueries({ queryKey: ["accounts"] }); if (mounted.current) toast.success("账号已删除") }, onError: (error) => { if (mounted.current) toast.error(error.message) } })
  const submit = () => { if (save.isPending) return; const next: Record<string, string> = {}; if (!draft.display_name.trim()) next.display_name = "请输入显示名称"; if (!draft.login_name.trim()) next.login_name = "请输入登录名"; if (editor === "new" && !draft.password) next.password = "请输入初始密码"; setErrors(next); if (!Object.keys(next).length) save.mutate() }
  if (!user.is_superuser) return <ErrorState error={new Error("需要超级管理员权限")} />
  const removeId = remove.isPending ? remove.variables : undefined
  return <div className="page-grid"><PageHeader title="账号管理" description="创建账号并维护权限、状态与登录凭据" actions={<Button onClick={() => openEditor("new")}><Plus data-icon="inline-start" />新建账号</Button>} /><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><SearchInput value={search} onChange={setSearch} placeholder="搜索账号" /><span className="text-xs text-muted-foreground">共 {filtered.length} 个账号</span></div>{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()} /> : !filtered.length ? <EmptyState title={search ? "没有匹配的账号" : "暂无账号"} description={search ? "调整搜索条件后再试。" : "创建第一个平台账号。"} /> : <Card className="overflow-x-auto"><Table className="dense-table"><TableHeader><TableRow><TableHead>显示名称</TableHead><TableHead>登录名</TableHead><TableHead>职位</TableHead><TableHead>角色</TableHead><TableHead>状态</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((account) => <TableRow key={account.id}><TableCell className="font-medium">{account.display_name}</TableCell><TableCell className="font-mono text-xs">@{account.login_name}</TableCell><TableCell>{account.job_title || "—"}</TableCell><TableCell>{account.is_superuser ? "超级管理员" : "普通账号"}</TableCell><TableCell><StatusBadge value={account.is_active === false ? "disabled" : "enabled"} /></TableCell><TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon-sm" aria-label={`编辑 ${account.display_name}`} onClick={() => openEditor(account)}><Pencil /></Button><Button variant="ghost" size="icon-sm" aria-label={`重置密码 ${account.display_name}`} disabled={reset.isPending && resetting?.id === account.id} onClick={() => { setResetting(account); setPassword("") }}><KeyRound /></Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`删除 ${account.display_name}`} disabled={removeId === account.id || account.id === user.id}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>永久删除账号？</AlertDialogTitle><AlertDialogDescription>删除 {account.display_name}（@{account.login_name}）后无法恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={remove.isPending} onClick={() => { if (!remove.isPending) remove.mutate(account.id) }}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableCell></TableRow>)}</TableBody></Table></Card>}
    <Dialog open={Boolean(editor)} onOpenChange={(value) => { if (!value && !save.isPending) setEditor(null) }}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{editor === "new" ? "新建账号" : "编辑账号"}</DialogTitle><DialogDescription>{editor === "new" ? "创建可立即登录平台的新账号。" : "修改资料、管理员角色和账号状态。"}</DialogDescription></DialogHeader><FieldGroup>{(["display_name", "job_title", "login_name"] as const).map((key) => <Field key={key} data-invalid={Boolean(errors[key])}><FieldLabel htmlFor={`managed-${key}`}>{({ display_name: "显示名称", job_title: "职位", login_name: "登录名" })[key]}</FieldLabel><Input id={`managed-${key}`} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} aria-invalid={Boolean(errors[key])} /><FieldError>{errors[key]}</FieldError></Field>)}{editor === "new" && <Field data-invalid={Boolean(errors.password)}><FieldLabel htmlFor="managed-password">初始密码</FieldLabel><Input id="managed-password" type="password" autoComplete="new-password" value={draft.password} onChange={(event) => setDraft({ ...draft, password: event.target.value })} aria-invalid={Boolean(errors.password)} /><FieldError>{errors.password}</FieldError></Field>}<Field orientation="horizontal"><FieldLabel htmlFor="managed-superuser">超级管理员</FieldLabel><Switch id="managed-superuser" aria-label="超级管理员" checked={draft.is_superuser} disabled={editor !== "new" && editor?.id === user.id} onCheckedChange={(is_superuser) => setDraft({ ...draft, is_superuser })} /></Field>{editor && editor !== "new" && <Field orientation="horizontal"><FieldLabel htmlFor="managed-active">账号启用</FieldLabel><Switch id="managed-active" aria-label="账号启用" checked={draft.is_active} disabled={editor.id === user.id} onCheckedChange={(is_active) => setDraft({ ...draft, is_active })} /></Field>}</FieldGroup><DialogFooter><Button variant="outline" disabled={save.isPending} onClick={() => setEditor(null)}>取消</Button><Button disabled={save.isPending} onClick={submit}>{save.isPending ? "保存中…" : editor === "new" ? "创建账号" : "保存更改"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(resetting)} onOpenChange={(value) => { if (!value && !reset.isPending) setResetting(null) }}><DialogContent><DialogHeader><DialogTitle>重置密码</DialogTitle><DialogDescription>为 {resetting?.display_name} 设置新密码；该账号的现有会话会失效。</DialogDescription></DialogHeader><Field><FieldLabel htmlFor="reset-account-password">重置后的新密码</FieldLabel><Input id="reset-account-password" type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /></Field><DialogFooter><Button variant="outline" disabled={reset.isPending} onClick={() => setResetting(null)}>取消</Button><Button disabled={!password || reset.isPending} onClick={() => { if (!reset.isPending) reset.mutate() }}><RotateCcw data-icon="inline-start" />{reset.isPending ? "重置中…" : "确认重置"}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
